[package]
name = "tunio-linux"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log.workspace = true
futures.workspace = true
netconfig.workspace = true
derive_builder.workspace = true
delegate.workspace = true
tunio-core.workspace = true
nix.workspace = true
libc.workspace = true

[features]
tokio = ["tunio-core/tokio"]
